theme: jekyll-theme-slate
site_favicon: favicon.ico
title: NRV Framework
description:  'NeuRon Virtualizer'
nrvxversion: 1.3.1
nrvxversiondate: October 2025

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      title: "NRV Framework"

url: https://nrv-framework.org
