name: Build & Upload Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false

      - name: Upgrade RubyGems and install Bundler
        run: |
          gem update --system 3.3.22
          gem install bundler -v 2.5.23

      - name: Install gems
        run: bundle _2.5.23_ install

      - name: Install ncftp
        run: sudo apt-get update && sudo apt-get install -y ncftp

      - name: Build Site with Jekyll
        run: bundle _2.5.23_ exec jekyll build

      - name: Upload site to SFTP
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 2222 ${{ secrets.FTP_HOST_VPS }} >> ~/.ssh/known_hosts
          
          # Sync via scp over SSH (delete and upload all files)
          ssh -i ~/.ssh/id_ed25519 -p 2222 -o StrictHostKeyChecking=no publishbot@${{ secrets.FTP_HOST_VPS }} 'rm -rf www/*'
          scp -r -i ~/.ssh/id_ed25519 -P 2222 -o StrictHostKeyChecking=no _site/* publishbot@${{ secrets.FTP_HOST_VPS }}:www/