name: Build & Upload Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false

      - name: Upgrade RubyGems and install Bundler
        run: |
          gem update --system 3.3.22
          gem install bundler -v 2.5.23

      - name: Install gems
        run: bundle _2.5.23_ install

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Build Site with Jekyll
        run: bundle _2.5.23_ exec jekyll build

      - name: Upload site to FTP
        env:
          ftp_location: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_LOGIN }}
          ftp_password: ${{ secrets.FTP_PASSWD }}
          ftp_folder: ${{ secrets.FTP_FOLDER }}
        run: |
          lftp -c "open ftp://$ftp_location; user $ftp_username $ftp_password; mirror --delete -R _site/ $ftp_folder"